### ISSUE TITLE
Renew access token on account_id change

### ISSUE THREAD

**Issue by mntzrr** [Dintero/Dintero.Checkout.WooCommerce.V2#136]
An access token needs to be updated in two cases:

- the `account_id` is changed.
- the user switches between test and production mode.

Currently, we remove the transient that store the access token _only_ when [the user switch between test mode](https://github.com/Dintero/Dintero.Checkout.WooCommerce.V2/blob/f52dc575f2988b4563314bd6f7ecddc8bf147d03/classes/class-dintero-checkout-settings-fields.php#L291-L294).  However, to ensure that the access token is updated in both scenarios, we should also check for changes to the `account_id`.

**Comment by andersem** [comment]
@mntzrr It should probably be changed if the `client_id` or `client_secret` is changed as well.
